name: Node.js CI
on: [push]
  
jobs:
  release:
    permissions:
      actions: read
      contents: write
      security-events: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm install pkg -g
    - run: pkg .
    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
        zip --junk-paths -m sync-dir-to-bucket.zip *sync-dir-to-bucket*
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./sync-dir-to-bucket.zip
        asset_name: sync-dir-to-bucket.zip
        asset_content_type: application/zip

#     - uses: actions-ecosystem/action-get-merged-pull-request@v1
#       id: get-merged-pull-request
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}

#     - uses: actions-ecosystem/action-release-label@v1
#       id: release-label
#       if: ${{ steps.get-merged-pull-request.outputs.title != null }}
#       with:
#         labels: ${{ steps.get-merged-pull-request.outputs.labels }}

#     - uses: actions-ecosystem/action-get-latest-tag@v1
#       id: get-latest-tag
#       if: ${{ steps.release-label.outputs.level != null }}
#       with:
#         semver_only: true

#     - uses: actions-ecosystem/action-bump-semver@v1
#       id: bump-semver
#       if: ${{ steps.release-label.outputs.level != null }}
#       with:
#         current_version: ${{ steps.get-latest-tag.outputs.tag }}
#         level: ${{ steps.release-label.outputs.level }}

#     - uses: actions-ecosystem/action-regex-match@v2
#       id: regex-match
#       if: ${{ steps.bump-semver.outputs.new_version != null }}
#       with:
#         text: ${{ steps.get-merged-pull-request.outputs.body }}
#         regex: '```release_note([\s\S]*)```'

#     - uses: actions-ecosystem/action-push-tag@v1
#       if: ${{ steps.bump-semver.outputs.new_version != null }}
#       with:
#         tag: ${{ steps.bump-semver.outputs.new_version }}
#         message: "${{ steps.bump-semver.outputs.new_version }}: PR #${{ steps.get-merged-pull-request.outputs.number }} ${{ steps.get-merged-pull-request.outputs.title }}"

#     - uses: actions/create-release@v1
#       if: ${{ steps.release-label.outputs.level == 'major' || steps.release-label.outputs.level == 'minor' }}
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ steps.bump-semver.outputs.new_version }}
#         release_name: ${{ steps.bump-semver.outputs.new_version }}
#         body: ${{ steps.regex-match.outputs.group1 }}

#     - uses: actions-ecosystem/action-create-comment@v1
#       if: ${{ steps.bump-semver.outputs.new_version != null }}
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         number: ${{ steps.get-merged-pull-request.outputs.number }}
#         body: |
#           The new version [${{ steps.bump-semver.outputs.new_version }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.bump-semver.outputs.new_version }}) has been released :tada:

