name: Node.js CI
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20.x'
    - run: npm ci
    - run: npm install pkg -g
    - run: pkg .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name:  ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.8.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: file-sync-to-gcp*
        tag: ${{ steps.tag_version.outputs.new_tag }}
        overwrite: true
        file_glob: true
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v3.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: release-output
        client-payload: '{"release": "${{ steps.tag_version.outputs.new_tag }}"}'
  
